/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['ageMax', 'ageMin', 'categorieId', 'clubId', 'createdAt', 'nom', 'saisonId', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column()
  declare ageMax: number | null
  @column()
  declare ageMin: number | null
  @column({ isPrimary: true })
  declare categorieId: bigint | number
  @column()
  declare clubId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare nom: string
  @column()
  declare saisonId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClubSchema extends BaseModel {
  static $columns = ['clubId', 'clubNomCourt', 'clubNomLong', 'createdAt', 'creationDate', 'description', 'statut', 'updatedAt'] as const
  $columns = ClubSchema.$columns
  @column({ isPrimary: true })
  declare clubId: bigint | number
  @column()
  declare clubNomCourt: string
  @column()
  declare clubNomLong: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare creationDate: DateTime
  @column()
  declare description: string | null
  @column()
  declare statut: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CotisationSchema extends BaseModel {
  static $columns = ['cotisationId', 'createdAt', 'dateDebutPaiement', 'dernierPaiement', 'methode', 'montant', 'saisonId', 'statut', 'updatedAt', 'userId'] as const
  $columns = CotisationSchema.$columns
  @column({ isPrimary: true })
  declare cotisationId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateDebutPaiement: DateTime | null
  @column.date()
  declare dernierPaiement: DateTime | null
  @column()
  declare methode: string | null
  @column()
  declare montant: string
  @column()
  declare saisonId: bigint | number
  @column()
  declare statut: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: bigint | number
}

export class EvenementSchema extends BaseModel {
  static $columns = ['adversaire', 'categorieId', 'clubId', 'competition', 'createdAt', 'dateHeure', 'description', 'estDomicile', 'evenementId', 'lieu', 'saisonId', 'scoreAdversaire', 'scoreNous', 'titre', 'type', 'updatedAt'] as const
  $columns = EvenementSchema.$columns
  @column()
  declare adversaire: string | null
  @column()
  declare categorieId: bigint | number
  @column()
  declare clubId: bigint | number
  @column()
  declare competition: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dateHeure: DateTime
  @column()
  declare description: string | null
  @column()
  declare estDomicile: boolean | null
  @column({ isPrimary: true })
  declare evenementId: bigint | number
  @column()
  declare lieu: string | null
  @column()
  declare saisonId: bigint | number
  @column()
  declare scoreAdversaire: number | null
  @column()
  declare scoreNous: number | null
  @column()
  declare titre: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'evenementId', 'notificationId', 'sendTime', 'statut', 'type', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare evenementId: bigint | number
  @column({ isPrimary: true })
  declare notificationId: bigint | number
  @column.dateTime()
  declare sendTime: DateTime | null
  @column()
  declare statut: string | null
  @column()
  declare type: string
  @column()
  declare userId: bigint | number
}

export class PresenceSchema extends BaseModel {
  static $columns = ['createdAt', 'evenementId', 'motif', 'presenceId', 'statut', 'updateTime', 'userId'] as const
  $columns = PresenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare evenementId: bigint | number
  @column()
  declare motif: string | null
  @column({ isPrimary: true })
  declare presenceId: bigint | number
  @column()
  declare statut: string | null
  @column.dateTime()
  declare updateTime: DateTime | null
  @column()
  declare userId: bigint | number
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'libelle', 'roleId', 'slug', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare libelle: string
  @column({ isPrimary: true })
  declare roleId: bigint | number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SaisonSchema extends BaseModel {
  static $columns = ['clubId', 'createdAt', 'dateDebut', 'dateFin', 'libelle', 'saisonId', 'statut', 'updatedAt'] as const
  $columns = SaisonSchema.$columns
  @column()
  declare clubId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateDebut: DateTime
  @column.date()
  declare dateFin: DateTime
  @column()
  declare libelle: string
  @column({ isPrimary: true })
  declare saisonId: bigint | number
  @column()
  declare statut: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['clubId', 'createdAt', 'roleId', 'userId'] as const
  $columns = UserRoleSchema.$columns
  @column()
  declare clubId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare roleId: bigint | number
  @column()
  declare userId: bigint | number
}

export class UtilisateurSchema extends BaseModel {
  static $columns = ['clubId', 'createdAt', 'dateDeNaissance', 'email', 'nom', 'password', 'prenom', 'statut', 'telephone', 'updatedAt', 'userId'] as const
  $columns = UtilisateurSchema.$columns
  @column()
  declare clubId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateDeNaissance: DateTime | null
  @column()
  declare email: string
  @column()
  declare nom: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare prenom: string
  @column()
  declare statut: string
  @column()
  declare telephone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare userId: bigint | number
}
