/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Categorie: () => import('#controllers/categorie_controller'),
  Club: () => import('#controllers/club_controller'),
  Cotisation: () => import('#controllers/cotisation_controller'),
  Evenement: () => import('#controllers/evenement_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Notification: () => import('#controllers/notification_controller'),
  Presence: () => import('#controllers/presence_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Saison: () => import('#controllers/saison_controller'),
  Utilisateur: () => import('#controllers/utilisateur_controller'),
}
